#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: e4456c87-92ee-4b4a-884b-5ada42c91d47
# Source File: C:\Users\MichaelTreml\OneDrive - Caf2Code LLC\Documents\SAPIEN\PowerShell Studio\Files\dd.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
IwMAAB+LCAAAAAAABABlk8mqo2AUhPeC7xDuVmhNNA6QG/iNMRo1xiFq3GmchziPT9+XNA0NXavi
VK0OXx308FWNYbtwXu9tfkyXVu/vL/zX7usIQ5vNQW3TOH17BZ8W4c0rw2MQ/Kq76ID+F3zqfNWW
x7HahhTbhDvwAuCkcifwRyw4bS1+2+5W8Ih0FLtPMZPShkosT36m2FwilsJeeBfZJjlC7k0R69m8
DckRpxYY0gnfv8qP5cS5F22IGkHNXziSUHRs1Fgk8CxhpG51VYbnw3Vqx9M4knAXyYxQM7abhkb0
K+aJZaxuTx4MGebZ56i1Ee1Ef/FKVYK8yiTpVd26lDBW5jRYnp9zSt6V56QsCNKi+Sd6Kq05vpbF
WL7xJyqQd4xHVBeGuiylc0WsFtMeXKtJeqweNLdc5Ch5XuRCkp7BXQaBnvqcZhAyLbLtUAm74raK
nMAzft2THmu/4lVsGBjaifLcqPKMVMXQCHUOulcW9w3eI4aPhhLx97+mYUX7aNRWCulx1sMLTm8Z
fKnm/jI5/ZZFZnWCoRq8pw4LgbWsozucxMJ/1N7WAXjmdPwyF0a1s1JEiRmQS9eY2Ar6wOxy/155
8dxlpQmoaa+zIOTugIUhcvdedNuc/LO9r9QhFm5ng3M7MChB4iRxNgfvNb9p2HXyUnJh2Oo5MJml
9CV1s87UyJCc0TqcO7aC6MAQjd05IVD4vdGbrzozA1nVHKnNUEzFlSAti5JCOhN/YGt0I0J9shVX
YK323pg1pbXP3sJkK6KD3Oi5Bwyphh5oQ5hndzzeS1kX7BPHfGvlQF5UdLraEy12HybB9/cB/aD6
gRZ0XVj6RRp2G/TnckD/HcXxN6hFtrwjAwAA#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2022 v5.8.206
     Generated on:       5/18/2022 7:23 AM
     Generated by:       MichaelTreml
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2022
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-dd_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$progressbar1 = New-Object 'System.Windows.Forms.ProgressBar'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		$file = 'C:\Users\MichaelTreml\Downloads\SPS22Setup_5.8.205_042622_x64.exe'
		$progressbar1.Maximum = (Get-Item $file).length/1MB
		$progressbar1.Value = 0
		$timeout = new-timespan -Hours 6
	}
	
	$button1_Click={
		#TODO: Place custom script here
		while ($progressbar1.Value -lt $progressbar1.Maximum)
		{
			$progressbar1.Value = $progressbar1.Value + 50
			$label1.Text = [String]$($($progressbar1.Value * 100) / $progressbar1.Maximum)
			start-sleep -seconds 1
		}
		
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$button1.remove_Click($button1_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($label1)
	$form1.Controls.Add($button1)
	$form1.Controls.Add($progressbar1)
	$form1.AutoScaleDimensions = New-Object System.Drawing.SizeF(6, 13)
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = New-Object System.Drawing.Size(426, 103)
	$form1.Margin = '2, 2, 2, 2'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# label1
	#
	$label1.AutoSize = $True
	$label1.Location = New-Object System.Drawing.Point(351, 37)
	$label1.Margin = '2, 0, 2, 0'
	$label1.Name = 'label1'
	$label1.Size = New-Object System.Drawing.Size(35, 13)
	$label1.TabIndex = 2
	$label1.Text = 'label1'
	#
	# button1
	#
	$button1.Location = New-Object System.Drawing.Point(35, 57)
	$button1.Name = 'button1'
	$button1.Size = New-Object System.Drawing.Size(75, 23)
	$button1.TabIndex = 1
	$button1.Text = 'button1'
	$button1.UseVisualStyleBackColor = $True
	$button1.add_Click($button1_Click)
	#
	# progressbar1
	#
	$progressbar1.Location = New-Object System.Drawing.Point(8, 8)
	$progressbar1.Name = 'progressbar1'
	$progressbar1.Size = New-Object System.Drawing.Size(413, 23)
	$progressbar1.TabIndex = 0
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-dd_psf | Out-Null

