 Invoke-DbaQuery -SqlInstance localhost -Database AxDB -Query "
  TRUNCATE TABLE SYSSERVERCONFIG
  TRUNCATE TABLE SYSSERVERSESSIONS
  TRUNCATE TABLE SYSCORPNETPRINTERS
  TRUNCATE TABLE SYSCLIENTSESSIONS
  TRUNCATE TABLE BATCHSERVERCONFIG
  TRUNCATE TABLE BATCHSERVERGROUP" | Out-File -FilePath $Logfile

