 WriteLog "Truncate Batch Tables"
  Invoke-D365SqlScript -Verbose -DatabaseServer localhost -DatabaseName AxDB -Command "
  TRUNCATE TABLE SYSSERVERCONFIG
  TRUNCATE TABLE SYSSERVERSESSIONS
  TRUNCATE TABLE SYSCORPNETPRINTERS
  TRUNCATE TABLE SYSCLIENTSESSIONS
  TRUNCATE TABLE BATCHSERVERCONFIG
  TRUNCATE TABLE BATCHSERVERGROUP"
  $mainprogressbaroverlay.PerformStep()
